version: '2'

services:
  php:
    build: ./docker/php
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASS: 123456
      DB_DATABASE: charts
    links:
      - mysql:mysql
    volumes:
      - "./config/php.ini:/usr/local/etc/php/php.ini"
      - "./app:/var/www/app"
  mysql:
    image: mysql:5.7
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: charts
    ports:
      - 3306:3306
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - "./config/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./app:/var/www/app"
    depends_on:
      - php
    links:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - 8080:80
    links:
        - mysql
    environment:
        PMA_HOST: mysql
